apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheussnapshot
spec:
  selector:
    matchLabels:
      app: prometheussnapshot
  template:
    metadata:
      labels:
        app: prometheussnapshot
    spec:
      containers:
      - name: prometheussnapshot
        image: ghcr.io/opscalehub/prometheussnapshot:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MINIO_ENDPOINT
          value: http://minio:9000
        - name: MINIO_ACCESS_KEY
          value: prometheus-snapshotter
        - name: MINIO_SECRET_KEY
          value: 9aa5782a-9e0c-4396-99ae-c8955f03f88c
        - name: MINIO_BUCKET
          value: prometheus-snapshots
        - name: MINIO_USE_SSL
          value: "false"
        - name: PROMETHEUS_URL
          value: http://prometheus-k8s.monitoring:9090
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "200m"
