apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2025-01-20T14-49-07Z
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name:  MINIO_ROOT_USER
          value: prometheus-snapshotter
        - name:  MINIO_ROOT_PASSWORD
          value: 9aa5782a-9e0c-4396-99ae-c8955f03f88c
        - name: MINIO_SERVER_URL
          value: https://minio.local.opscale.ir
        - name: MINIO_BROWSER_REDIRECT_URL
          value: https://minio.local.opscale.ir/console
        - name: MINIO_PUBLIC_URL
          value: https://minio.local.opscale.ir
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: minio-data
          mountPath: "/data"
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-data