apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
stringData:
  MINIO_ROOT_USER: prometheus-snapshotter
  MINIO_ROOT_PASSWORD: 9aa5782a-9e0c-4396-99ae-c8955f03f88c
  MINIO_PUBLIC_URL: http://localhost:9000
  MINIO_BROWSER_REDIRECT_URL: http://localhost:9001